name: Terraform Plan on PR

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color | grep -A20 'Terraform will perform the following actions' > plan.txt > plan.txt
          echo "PLAN_OUTPUT<<EOF" >> $GITHUB_ENV
          cat plan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # - name: Comment on PR
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     message: |
      #       ## 📌 Terraform Plan Result
      #       ```
      #       ${{ env.PLAN_OUTPUT }}

      - name: Comment on PR
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## 📌 Terraform Plan Result
          ```
          ${{ env.PLAN_OUTPUT }}
          ```
    