name: ECR Build Manual Approval Workflow
on:
  push:
    branches:
      - main
      - staging
      - dev
    paths-ignore:
      - 'README.md'
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
  manual-approval:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.ACCESS_TOKEN }}
          approvers: 'shaoyunjian'
          minimum-approvals: 1
          issue-title: "Deploying version ${{ github.sha }} to prod from staging"
          issue-body: "Please approve or deny the deployment of version ${{ github.sha }}."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [build, manual-approval]
    if: always()
    steps:
      - name: print job status
        run: |
          echo "Build job status: ${{ needs.build.result }}"
      - name: print job status
        run: |
          echo "Build job status: ${{ needs.manual-approval.result }}"
