name: ECR Build Manual Approval Workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs: 
  deploy:
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TW_CI_URL }}
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get commit message and escape for JSON
        id: get_commit_msg
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          ESCAPED_COMMIT_MSG=$(jq -Rs <<< "$COMMIT_MSG")
          echo "escaped_commit_message=$ESCAPED_COMMIT_MSG" >> "$GITHUB_OUTPUT"

      - name: Trigger when succeeded
        run: |
          actions_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H "Content-Type: application/json" -d '{
            "channel": "#alerts-channel",
            "icon_emoji": ":white_check_mark:",
            "attachments": [
              {
                "text": ":tada: Image Build and Push to ECR Completed!\n• Repo: '"${{ github.repository }}"'\n• Committer: '"${{ github.event.pusher.name }}"'\n• Commit Message: '"${{ steps.get_commit_msg.outputs.escaped_commit_message }}"'\n• <'"$actions_url"'|GitHub Action>",
                "color": "#36a64f",
                "attachment_type": "default"
              }
            ]
          }' "$SLACK_WEBHOOK_URL"
