name: ECR Build Manual Approval Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TW_CI_URL }}
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get commit message
        run: |
          echo "GIT_COMMIT_MESSAGE<<EOF" >> "$GITHUB_ENV"
          git log -1 --pretty=%B >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - name: test
        run: |
          # 注意：這裡用 $GIT_COMMIT_MESSAGE，而不是 GitHub Actions 的語法
          commit_message=$(jq -Rs <<< "$GIT_COMMIT_MESSAGE")
          echo "$commit_message"
          echo "\"$commit_message\""

      - name: Trigger when succeeded
        run: |
          commit_message=$(jq -Rs <<< "$GIT_COMMIT_MESSAGE")
          actions_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          payload='{
            "channel": "#alerts-channel",
            "icon_emoji": ":white_check_mark:",
            "attachments": [
              {
                "text": ":tada: Image Build and Push to ECR Completed!\n• Repo: shaoyunjian/github-actions-test\n• Committer: shaoyunjian\n• Commit Message: '"$commit_message"'\n• <'"$actions_url"'|GitHub Action>",
                "color": "#36a64f",
                "attachment_type": "default"
              }
            ]
          }'


          curl -X POST -H "Content-Type: application/json" -d "$payload" "$SLACK_WEBHOOK_URL"

